export const SET_FILM='SET_FILM';
export const SET_PHIM_DANG_CHIEU='SET_PHIM_DANG_CHIEU';
export const SET_PHIM_SAP_CHIEU='SET_PHIM_SAP_CHIEU';

export const SET_PHIM_DETAIL='SET_PHIM_DETAIL';

export const SET_THONG_TIN_PHIM='SET_THONG_TIN_PHIM';