export const SET_THONG_TIN_PHONG_VE='SET_THONG_TIN_PHONG_VE';
export const SET_GHE_DANG_DAT='SET_GHE_DANG_DAT';
export const SET_THONG_TIN_DAT_VE='SET_THONG_TIN_DAT_VE';

export const CLEAR_GHE_DANG_DAT='CLEAR_GHE_DANG_DAT';

export const CHUYEN_TAB='CHUYEN_TAB';
export const CHANGE_TAB_ACTIVE='CHANGE_TAB_ACTIVE'; 