export const SET_USER_LOGIN='SET_USER_LOGIN';
export const SET_THONG_TIN_NGUOI_DUNG='SET_THONG_TIN_NGUOI_DUNG';
export const SET_DANH_SACH_NGUOI_DUNG='SET_DANH_SACH_NGUOI_DUNG';
export const SET_DANH_SACH_LOAI_NGUOI_DUNG='SET_DANH_SACH_LOAI_NGUOI_DUNG';
export const EDIT_NGUOI_DUNG='EDIT_NGUOI_DUNG';